DFE-Digital/improve-workload-and-wellbeing-for-school-staff

content/index.html, layouts/default.html
There are issues finding assets in GitHub pages. The assests are expected at the project root, but in GitHub pages they are under the sub-directory `improve-school-workload-and-wellbeing`
This PR adjusts the css and images paths to be relative.
=> Use relative paths for assets

layouts/default.html
Start setting up analytics - https://trello.com/c/xD2BSa0x
As per the setup [instructions](https://support.google.com/analytics/answer/9304153) we are adding the customised script tag to the `head` section of all pages.
=> Add Google Analytics

content/explore-all-resources/evaluate-workload-measures.html.erb
There's a typo I missed when reviewing the PR for the Explore all resources page.
It changes it from 'create' to 'created'.
=> Fix typo on explore resources evaluate page

content/workload-reduction-toolkit/how-the-toolkit-was-made.md
For accessibility reasons, we're removing links that open in a new tab.
We need to get rid of the text, and the functionality that causes the link to open in a new tab.
This follows guidance on links in new tabs from GOVUK: https://design-system.service.gov.uk/styles/links/#opening-links-in-a-new-tab
=> Remove links to open in new tab

content/explore-all-resources/communications.html.erb, content/workload-reduction-toolkit/address-workload-issues/communications.html.erb, content/workload-reduction-toolkit/address-workload-issues/communications/parental-communications-policy.md
This PR can be used as an example of how to add a new resource.
- Added new Parental communications policy resource, accessible at `/workload-reduction-toolkit/address-workload-issues/communications/parental-communications-policy`
- Linked new page from 'Explore all resources' page
- Linked new page from 'Communications' topic page
https://trello.com/c/obcz4Lqt/285-create-instructions-for-content-designers-and-devs-to-create-and-approve-pull-requests-for-the-service
=> [285] Add 'Parental communications policy' resource

content/assets/css/_info-box.scss, content/assets/css/application.scss, content/explore-all-resources/staff-wellbeing.html.erb, content/staff-wellbeing.html.erb, content/staff-wellbeing/establish-a-wellbeing-committee.md, docs/adding-a-resource.md, layouts/markdown_resource.html.erb
- Adds 'Establish a wellbeing committee' resource
- Adds link to this resource
- Adds new front matter option `colour`.
- This defaults to purple (all existing resources are purple) 
- Give the value `blue` to change inset text colour and info box to blue
https://trello.com/c/Xd4jMGkr/312-create-the-first-wellbeing-individual-resource
- Check new resource looks ok and links work
- Check that there are no regressions for existing resources in terms of colour scheme
=> [312] Add first wellbeing resource with 'colour scheme' feature

content/assets/css/_cards.scss, content/assets/css/_feedback-sections.scss, content/assets/css/application.scss, content/main.html.erb, content/share-your-ideas.html.erb, content/workload-reduction-toolkit.html.erb, content/workload-reduction-toolkit/address-workload-issues.html.erb, layouts/base.html, layouts/workload_topic_section.html.erb
- Add viewport meta tag so that the site is correctly sized on all devices
- Mobile style updates (see screenshots below)
- Fix hover/active styles on homepage links
- Check hover and active styles for 'Staff wellbeing' and 'Workload reduction' box links.
- the whole box is now clickable
- your cursor turns to a pointer and text becomes underlined on hover (over whole box)
- blue header turns yellow when active, not just the text
- the text turns black when active, not white
- Before and after screenshots for active style:
Visit the site on a mobile or right click -> inspect the page in the browser and view as different devices.
Check that all pages look better!
Things I've fixed (left screenshots are my fixes, right screenshots are currently in production):
---
---
---
---
---
---
=> [308 & 311] Mobile styling and homepage links

content/assets/css/_info-box.scss, content/assets/css/application.scss, content/workload-reduction-toolkit.html.erb, content/workload-reduction-toolkit/identify-workload-issues.html.erb
- Add identify section with pink info box
https://trello.com/c/rCTLRzXY/309-build-identify-section-page
- Navigate to identify section page from workload reduction toolkit and check content
=> [309] Add identify section page

lib/filters/base_url_filter.rb
I realised the mailto links didn't work. This is because the filter to make them external only applied for links starting with http and /. But the email link begins with mailto.
I've added mailto to the filter.
=> Fixing our mailto links

content/workload-reduction-toolkit/address-workload-issues/communications/review-and-streamline-communications.html.erb, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-and-streamline-feedback-and-marking.html.erb, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-marking-practice-with-an-impact-matrix.md, content/workload-reduction-toolkit/identify-workload-issues/staff-workload-survey.md
Quick updates to html of download boxes on feedback and marking resources to remove `<ul>` and tidy up some classes we don't need anymore.
=> Update html of download boxes on feedback and marking resources

layouts/base.html, layouts/partials/tag_manager_body.html.erb, layouts/partials/tag_manager_head.html.erb
Card: [Set up consent mode](https://trello.com/c/4wGRCdBZ)
We have created the "Consent Status" Data Layer Variable in [Google Tag Manager](https://tagmanager.google.com/?utm_campaign=SuiteHeader&utm_source=UniversalPicker&utm_medium=getStarted#/container/accounts/6218708721/containers/178350106/workspaces/2/variables) (GTM).
We tested in [GTM](https://tagassistant.google.com/#/?source=TAG_MANAGER&id=GTM-MFJXR544&gtm_auth=v6h5KWgFamt_cahYRuhUYw&gtm_preview=env-4&cb=2581910948753181) using the preview [app](https://deploy-preview-61--iwwss-review.netlify.app/main/).
Check that you can access [Google Tag Manager](https://tagmanager.google.com/?utm_campaign=SuiteHeader&utm_source=UniversalPicker&utm_medium=getStarted#/container/accounts/6218708721/containers/178350106/workspaces/2/variables)
=> Add google tag manager

Rules, content/staff-wellbeing/establish-a-wellbeing-committee.md, content/staff-wellbeing/supporting-staff-mental-health.md, content/workload-reduction-toolkit/address-workload-issues/communications/parental-communications-policy.md, content/workload-reduction-toolkit/address-workload-issues/communications/school-email-protocol.md, content/workload-reduction-toolkit/address-workload-issues/communications/streamline-internal-school-communications.md, content/workload-reduction-toolkit/address-workload-issues/communications/switch-to-online-parents-evenings.md, content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/change-lesson-observations-to-class-visits.md, content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/develop-a-culture-of-support-and-staff-development.md, content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/try-ideas-to-manage-planning.md, content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/use-time-effectively.md, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/cut-down-your-marking-workload.md, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/give-feedback-and-avoid-marking-in-primary-schools.md, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/give-feedback-effectively-without-creating-an-unmanageable-workload.md, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/improve-how-you-give-feedback-to-primary-pupils.md, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-marking-practice-with-an-impact-matrix.md, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/secondary-school-feedback-policy.md, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/try-ideas-to-manage-feedback-and-marking.md, content/workload-reduction-toolkit/how-the-toolkit-was-made.md, content/workload-reduction-toolkit/identify-workload-issues/staff-workload-survey.md, docs/adding-a-resource.md, docs/example-resource.md
- We have lots and LOTS of markdown pages now, but only two of them use the `markdown_layout.html.erb` specified as default in the `Rules` file
- The vast majority are using the `markdown_resource.html.erb` layout which needs to be specified in each front matter
- Make the `markdown_resource.html.erb` layout default. This makes sense for future development because more markdown resources are likely to be added by non-devs
- No visual changes.
=> [xxx] Refactor markdown layouts

content/explore-all-resources/staff-wellbeing.html.erb, content/staff-wellbeing.html.erb, content/staff-wellbeing/academy-trust-workload-agreement.md, content/staff-wellbeing/communicate-about-wellbeing-to-improve-staff-retention.md, content/staff-wellbeing/create-a-school-culture-which-improves-wellbeing.md, content/staff-wellbeing/establish-a-school-workload-group.md, content/staff-wellbeing/make-a-list-of-everything-you-do-to-improve-wellbeing.md, content/staff-wellbeing/protect-staff-time-and-improve-wellbeing.md, content/staff-wellbeing/staff-wellbeing-policy.md, content/staff-wellbeing/staff-wellbeing-statement.md, content/staff-wellbeing/try-ideas-to-improve-staff-wellbeing.md, content/workload-reduction-toolkit/address-workload-issues/behaviour-management/set-out-a-clear-and-consistent-approach-to-behaviour-management.md, content/workload-reduction-toolkit/address-workload-issues/behaviour-management/set-up-a-centralised-system-to-record-monitor-and-reward-pupil-behaviour.md, content/workload-reduction-toolkit/address-workload-issues/behaviour-management/try-ideas-to-manage-behaviour-management-workload.md, content/workload-reduction-toolkit/address-workload-issues/communications/school-email-protocol.md
Guide to review:
- Check all the links work
- Check for typos or mistakes
- Check all the wellbeing resources are represented
- Check the info for each resource is correct on the staff wellbeing or explore resources page
Questions for design: Should the tag be 'wellbeing' or 'staff wellbeing' on the explore resources page?
I'm not entirely comfy with how the links are the same size as the Headers like 'set a wellbeing vision' - I think this might be an accessibility issue. How should we handle this?
=> Add wellbeing resources and links

content/explore-all-resources/identify-workload-issues.html.erb, content/workload-reduction-toolkit/address-workload-issues/behaviour-management/review-and-streamline-behaviour-management.html.erb, content/workload-reduction-toolkit/address-workload-issues/communications/review-and-streamline-communications.html.erb, content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/review-and-streamline-lesson-planning.html.erb, content/workload-reduction-toolkit/address-workload-issues/data-management/review-and-streamline-data-management.html.erb, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-and-streamline-feedback-and-marking.html.erb, content/workload-reduction-toolkit/identify-workload-issues.html.erb, content/workload-reduction-toolkit/identify-workload-issues/act-on-your-staff-workload-survey.md, content/workload-reduction-toolkit/identify-workload-issues/create-an-action-plan-to-reduce-workload.md, content/workload-reduction-toolkit/identify-workload-issues/have-structured-conversations-to-identify-issues.md, content/workload-reduction-toolkit/identify-workload-issues/how-we-addressed-workload-issues.md, content/workload-reduction-toolkit/identify-workload-issues/plan-your-yearly-calendar.md, content/workload-reduction-toolkit/identify-workload-issues/prioritise-change-using-impact-graphs.md, content/workload-reduction-toolkit/identify-workload-issues/share-progress-with-staff.md, content/workload-reduction-toolkit/identify-workload-issues/staff-workload-survey.md, content/workload-reduction-toolkit/identify-workload-issues/use-an-inset-day-to-focus-on-reducing-workload.md
- Adds all remaining identify resources with pink colour scheme
- **BONUS**: I reviewed all the info-box icons across the site and fixed some alt texts. I swapped some presentation icons to be the download icon as per prototype.
Any downloads or updates to the download box for two links.
https://trello.com/c/WFCQiHAR/336-add-the-rest-of-the-identify-resources
- Check content of each resource
- Check links WITHIN each resource
- Check that the resources are linked to correctly from the identify page and the explore resources area
=> [336] Add all identify resources

content/assets/css/_feedback-sections.scss, content/assets/css/application.scss, content/staff-wellbeing.html.erb, content/workload-reduction-toolkit/address-workload-issues/communications/review-and-streamline-communications.html.erb, content/workload-reduction-toolkit/address-workload-issues/data-management/review-and-streamline-data-management.html.erb, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-and-streamline-feedback-and-marking.html.erb, content/workload-reduction-toolkit/evaluate-workload-measures.html.erb, content/workload-reduction-toolkit/identify-workload-issues.html.erb, layouts/markdown_resource.html.erb, layouts/workload_topic_section.html.erb
- Remove the section breaks from above main text on all pages (topic pages and resources)
- Add section breaks above feedback sections
https://trello.com/c/2GV9ReTV/343-remove-horizontal-break-lines-on-main-text-and-add-horizontal-break-line-above-share-your-ideas
- Check that the section break colours match which section they're in
- Check we're not missing any
- Check it looks ok on mobile
=> [343] Horizontal line colours

content/main.html.erb, content/workload-reduction-toolkit.html.erb, layouts/base.html.erb
- Swap the order of 'Staff wellbeing' and 'Workload reduction toolkit' boxes on the main page
- Swap the links in the navbar
- Make the headings of the boxes on the main page `<h2>`s
- Make the headings of the boxes on the Workload reduction toolkit `<h3>`s
=> [342] Swap order of sections and make titles HTML headings

content/assets/css/_info-box.scss, content/assets/css/application.scss, layouts/markdown_layout.html.erb, layouts/markdown_resource.html.erb
1. Remove the `.markdown-page` class from the `markdown_layout` file.
This layout is only used by **two (non resource) pages**:
- Supporting staff mental health in schools `/staff-wellbeing/supporting-staff-mental-health/`
- Accessibility statement 
Neither of these pages need the css that this class applies (most obviously the large margins around h2s)
2. Rename the class `.markdown-resource` so it more accurately reflects what it encompasses
=> [xxx] Tweak to css on markdown pages

content/assets/css/_cards.scss, content/main.html.erb, content/workload-reduction-toolkit.html.erb, layouts/partials/tile.html.erb
- Add new mobile styles for the tiles on both the homepage and the workload toolkit
- Move tiles into reusable partial
- Check that there are no regressions on desktop
- Check styles on mobile
New mobile style:
=> [366] Mobile tiles

layouts/partials/cookies_banner.html.erb, layouts/partials/feedback.html.erb, layouts/partials/share_this_resource.html.erb, layouts/partials/topic_list.html.erb, lib/helpers.rb
[Fix the email link on individual resources](https://trello.com/c/wFYSScv2)
`@base_url` is not processed in partials. We could see the result of this when clicking the "Email" link in the partial `layouts/partials/share_this_resource.html.erb`. The result being that the base path of the URl was missing.
To resolve this we have added a helper method `base_url` to `layouts/partials/share_this_resource.html.erb` and updated occurrences of `@base_url` in partials to `base_url`.
Check:
=> Fix `base_url` in partials

content/assets/css/application.scss, content/workload-reduction-toolkit/address-workload-issues/behaviour-management/review-and-streamline-behaviour-management.md, content/workload-reduction-toolkit/address-workload-issues/communications/review-and-streamline-communications.html.erb, content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/review-and-streamline-lesson-planning.md, content/workload-reduction-toolkit/address-workload-issues/data-management/review-and-streamline-data-management.html.erb, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-and-streamline-feedback-and-marking.html.erb, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-marking-practice-with-an-impact-matrix.md, content/workload-reduction-toolkit/evaluate-workload-measures/evaluate-progress-with-staff.md, content/workload-reduction-toolkit/evaluate-workload-measures/staff-workload-survey.md, content/workload-reduction-toolkit/evaluate-workload-measures/structured-conversations-with-staff.md, content/workload-reduction-toolkit/evaluate-workload-measures/update-your-workload-action-plan.md, content/workload-reduction-toolkit/identify-workload-issues/act-on-your-staff-workload-survey.md, content/workload-reduction-toolkit/identify-workload-issues/create-an-action-plan-to-reduce-workload.md, content/workload-reduction-toolkit/identify-workload-issues/have-structured-conversations-to-identify-issues.md, content/workload-reduction-toolkit/identify-workload-issues/plan-your-yearly-calendar.md, content/workload-reduction-toolkit/identify-workload-issues/prioritise-change-using-impact-graphs.md, content/workload-reduction-toolkit/identify-workload-issues/share-progress-with-staff.md, content/workload-reduction-toolkit/identify-workload-issues/staff-workload-survey.md, layouts/partials/share_this_resource.html.erb
- Remove 'govuk-link--no-visited-state' class from download links
- Fix styles on share links so that the standard govuk yellow background is applied when active
https://trello.com/c/bjyMFQ4m/397-fix-active-states-on-copy-link-and-email-link-and-remove-no-visited-state-class-on-download-links
- On resources, check that the download links turn purpler once visited
- Check that the active styles for both links in the Share this resource section are correct (standard yellow)
=> [397] Link styles

content/cookie-policy.html.erb
Allow an optional line break in the cookie name so that the table doesn't bleed off screen at 400%.
https://trello.com/c/LdzIyc8O/398-fix-text-bleed-at-400-zoom
Zoom in browser to 400% and check the cookies table fits on the screen:
Investigated keeping the footer from touching the edge of the screen but we're limited by the length of our email address:
=> [398] Text bleed on cookies page at 400%

content/assets/css/_cards.scss, layouts/partials/explore_resource_card.html.erb
Added margin to the tags on the explore resources pages.
Investigated making the font smaller on mobile, but it's already at the smallest recommended font size (16px).
May improve further when [this PR](https://github.com/DFE-Digital/improve-workload-and-wellbeing-for-school-staff/pull/93) is merged (it reduces the borders on mobile)
https://trello.com/c/sTEOHWkT/404-investigate-section-tags-on-the-explore-resources-page-potentially-making-the-font-smaller-or-tweaking-the-spacing
Head to the explore resources page and check that the tags look better.
=> [404] Add margin to bottom of explore resource tags

content/assets/css/application.scss, layouts/base.html.erb
To try to resolve this we have removed the `max-width` of the header logo and text. This results in the menu button moving below the header and closer to where the menu will appear.
https://github.com/DFE-Digital/improve-workload-and-wellbeing-for-school-staff/assets/85567720/ccfa75de-4eed-433d-943f-c50cfe6f47a7
=> Apply fixes from cognitive walkthrough

layouts/base.html.erb, layouts/partials/skip_link.html.erb
https://github.com/DFE-Digital/improve-workload-and-wellbeing-for-school-staff/assets/85567720/dd69a6c3-fc9f-473b-94f2-7d172f64197e
=> Add skip link for screen readers

content/staff-wellbeing.html.erb
=> Amend wellbeing box on homepage and wellbeing main page

content/assets/css/_cards.scss, content/assets/css/_feedback-sections.scss, content/assets/css/application.scss, content/index.html.erb, content/workload-reduction-toolkit.html.erb, layouts/partials/tile.html.erb
- Fix spacing around homepage tiles
- Update content on wellbeing tile
- Ensure homepage tiles stay the same size with different length content
- Fix spacing on Explore all resources section
- Fix spacing on full-width 'Share your ideas' and 'Help improve our service' section
- Fix spacing around Workload reduction toolkit 'Use the toolkit' title
- Compare pages to screenshots on Trello ticket: https://trello.com/c/F2Ov4Eeg/407-adjust-padding-and-spacing-for-the-main-landing-page-toolkit-landing-page
- **IMPORTANT** - check the page on mobile to check things still look ok!!
=> [407] Fix spacing and update content on homepage

content/assets/css/_feedback-sections.scss, layouts/partials/feedback.html.erb
For 'Share your ideas' and 'Help improve our service' boxes in resources and topic pages:
- Position the icon in the same row as the heading
- Align the paragraph below so that it appears below the icon.
I achieved by including a second icon shown on resource pages but hidden on the homepage. The larger left-aligned homepage icon is conversely hidden on resource pages.
- Check the styling of the section on resource pages
- Check the styling is not broken on the homepage and Workload reduction toolkit page. They should be unchanged here.
- Check on mobile
=> [416] Style tweaks to feedback sections on resource pages

content/workload-reduction-toolkit/address-workload-issues/communications/review-and-streamline-communications.html.erb, content/workload-reduction-toolkit/address-workload-issues/data-management/review-and-streamline-data-management.html.erb, content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-and-streamline-feedback-and-marking.html.erb
For the content to render correctly, the `dfe-width-container` div should wrap the `govuk-grid-row` div. This was incorrect on a couple of pages to the content wasn't aligning properly e.g. on Communications presentation:
Now:
=> Move `dfe-width-container` outside of `govuk-grid-row` on resources

docs/adding-a-resource.md, docs/example-presentation.html.erb
Adding an example presentation page in the `docs` folder and linking to it from the "Adding a Resource" page.
=> Add presentation page template
