DFE-Digital/improve-workload-and-wellbeing-for-school-staff

- .github/workflows/dependabot-auto-merge.yml
This pull request introduces a new GitHub workflow aimed at automating the merge process for minor updates from Dependabot. The goal is to streamline the dependency management process, ensuring our project stays up-to-date with the latest minor patches and updates without manual intervention, while still maintaining a high standard of code quality and stability.
New Workflow File: Added GitHuib workflow, which contains the logic for automatically merging pull requests from Dependabot.
**Auto-Merge Criteria:** The workflow is configured to automatically merge pull requests only if:
- The pull request is opened by Dependabot.
- The update is a minor version change (patch updates).
- All status checks (like CI build and tests) pass successfully.
**Safety Measures:** To ensure the stability …
> Implement Auto-Merge for Minor Dependabot Updates

- content/main.html.erb
This is a small content change to note that the resources are free.
> Add that resources are free

- content/assets/css/application.scss
- layouts/partials/feedback.html
Card [Feedback section styling](https://trello.com/c/5UmwTvIJ)
Corrected the styling of the feedback section based on the card comments
> Improve feedback section styling

- content/workload-reduction-toolkit/address-workload-issues/communications/switching-to-online-parents-evenings.md
There have been some content updates.
Question: Your wrapping on the text is much nicer. How do I do that?!
> Update the content for the parents evening resource

- content/assets/css/_feedback-sections.scss
- content/assets/css/application.scss
- content/workload-reduction-toolkit/address-workload-issues/communications/switching-to-online-parents-evenings.md
- layouts/markdown_resource.html.erb
Increase the margin above the feedback section for the individual resources.
Remove the top horizontal rules.
> Increase margin on resource layout above feedback section

- layouts/base.html
- lib/helpers.rb
- lib/helpers/navigation_helper.rb
Card: ['Active' styling on navigation tabs](https://trello.com/c/vK4CoB2S)
Add nav link highlighting.
> Add nav link highlighting

- layouts/base.html
- layouts/partials/analytics.html.erb
Card: [Investigate why Google Analytics has stopped working](https://trello.com/c/QmMi0fZ8)
Re-add the Google Analytics script.
You can test with `https://deploy-preview-55--iwwss-review.netlify.app/main/` [here](https://analytics.google.com/analytics/web/#/a299519693p424020618/admin/streams/table/6657503176).
> Re-add Google Analytics

- Gemfile
- Gemfile.lock
- Rules
- content/workload-reduction-toolkit/how-the-toolkit-was-made.md
I spoke with Pete about how straight quotes were driving me mad. He suggested installing this ruby pants gem to make them curly.
> Trying ruby pants out to try and fix straight quotes.

- content/main.html.erb
- layouts/base.html.erb
Card: [Fixes for development after testing](https://trello.com/c/TSKSJhiJ)
Very minor fixes after UR testing
> Minor updates after UR

- content/explore-all-resources/evaluate-workload-measures.html.erb
- content/workload-reduction-toolkit/evaluate-workload-measures.html.erb
- content/workload-reduction-toolkit/evaluate-workload-measures/staff-workload-survey.md
- content/workload-reduction-toolkit/identify-workload-issues/staff-workload-survey.md
- Add evaluate workload measures survey
- Links to survey from evaluate page and explore resources page
**No download file yet - changes still being made to survey**
https://trello.com/c/Gz3mzzqT/340-create-evaluate-survey-page
> [340] Add evaluate survey page

- content/assets/javascripts/cookies_banner.js
This PR introduces the integration of user consent status into the data layer to manage Google Analytics tracking in compliance with privacy regulations. We have updated our website's JavaScript to push the user's consent choice to the data layer, which can be utilised by Google Tag Manager (GTM) to conditionally trigger tags based on consent.
We have already created a Data Layer Variable in GTM to store the value for `consentUpdate`. It is defaulted to false.
- Added `dataLayer.push()` calls within the `accept()` and `reject()` functions in our website's JavaScript to record the user's consent status.
- Introduced an event `consentUpdate` within the `dataLayer.push()` calls to serve as a trigger for Google Tag Manager.
- Established a new Data Layer Variable in GTM named `consentStatus`, …
> Implement User Consent Status Tracking for GA via Data Layer

- content/explore-all-resources/staff-wellbeing.html.erb
- content/staff-wellbeing.html.erb
- content/staff-wellbeing/make-a-list-of-everything-you-do-to-improve-wellbeing.md
- content/staff-wellbeing/staff-wellbeing-policy.md
- content/staff-wellbeing/try-ideas-to-improve-staff-wellbeing.md
- content/staff-wellbeing/wellbeing-and-workload-charter.md
I found some problems in staff wellbeing once it was merged.
This includes adding the staff wellbeing resource that I forgot to add.
> Make fixes to the staff wellbeing resources

- docs/analytics-overview.md
This PR introduces high-level documentation, describing our implementation strategy for Google Analytics 4 (GA4), Google Tag Manager (GTM), the use of cookies, and the user consent banner on our website.
The purpose of this documentation is to:
- Provide clarity on how we implement and utilise GA4 and GTM.
- Outline our use of cookies in compliance with privacy regulations.
- Explain the functionality and necessity of the user consent banner.
- Detail the data privacy and user control measures we have in place.
- No impact on the existing codebase or functionality.
- Provides a reference for team members and stakeholders on our consent management practices.
- Ensures transparency in our analytics and data collection methods.
- Please read through the document to verify the accuracy of the …
> Documentation for Analytics and Consent Management Implementation

- content/workload-reduction-toolkit/evaluate-workload-measures/staff-workload-survey.md
- content/workload-reduction-toolkit/identify-workload-issues/staff-workload-survey.md
- Add `<h2>`s to info boxes 'Edit the survey'
- Fix titles to match change log
- Fix typo
**Not done:**
- Adding 2 x downloads
> [357] Tweaks to survey pages

- docs/adding-a-resource.md
Remove TODO in docs which is now covered in section above talking about colour scheming.
> Remove TODO in docs

- content/explore-all-resources/behaviour-management.html.erb
- content/explore-all-resources/communications.html.erb
- content/explore-all-resources/curriculum-planning-and-delivery.html.erb
- content/explore-all-resources/feedback-and-marking.html.erb
- content/explore-all-resources/identify-workload-issues.html.erb
- content/explore-all-resources/staff-wellbeing.html.erb
- content/staff-wellbeing.html.erb
- content/staff-wellbeing/academy-trust-workload-agreement.md
- content/staff-wellbeing/communicate-about-wellbeing-to-improve-staff-retention.md
- content/staff-wellbeing/create-a-school-culture-which-improves-wellbeing.md
- content/staff-wellbeing/try-ideas-to-improve-staff-wellbeing.md
- content/workload-reduction-toolkit/address-workload-issues/behaviour-management.html.erb
- content/workload-reduction-toolkit/address-workload-issues/behaviour-management/set-up-a-centralised-system-to-record-monitor-and-reward-pupil-behaviour.md
- content/workload-reduction-toolkit/address-workload-issues/communications.html.erb
- content/workload-reduction-toolkit/address-workload-issues/communications/parental-communications-policy.md
- content/workload-reduction-toolkit/address-workload-issues/communications/school-email-protocol.md
- content/workload-reduction-toolkit/address-workload-issues/communications/streamline-internal-school-communications.md
- content/workload-reduction-toolkit/address-workload-issues/communications/switch-to-online-parents-evenings.md
- content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery.html.erb
- content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/change-lesson-observations-to-class-visits.md
- content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/try-ideas-to-manage-planning.md
- content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/use-time-effectively.md
- content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking.html.erb
- content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-marking-practice-with-an-impact-matrix.md
- content/workload-reduction-toolkit/evaluate-workload-measures.html.erb
- content/workload-reduction-toolkit/identify-workload-issues.html.erb
- content/workload-reduction-toolkit/identify-workload-issues/use-an-inset-day-to-focus-on-reducing-workload.md
- docs/adding-a-resource.md
- docs/removing-a-resource.md
Based on the details in the change log, fixed:
- school names
- reading times
- resource types
- titles
> [331] Update school names and resource details

- content/explore-all-resources/evaluate-workload-measures.html.erb
- content/workload-reduction-toolkit/evaluate-workload-measures.html.erb
- content/workload-reduction-toolkit/evaluate-workload-measures/evaluate-progress-with-staff.md
- content/workload-reduction-toolkit/evaluate-workload-measures/staff-workload-survey.md
- content/workload-reduction-toolkit/evaluate-workload-measures/structured-conversations-with-staff.md
- content/workload-reduction-toolkit/evaluate-workload-measures/update-your-workload-action-plan.md
Updated files:
- `/workload-reduction-toolkit/evaluate-workload-measures.html.erb`
Added files:
- `/workload-reduction-toolkit/evaluate-workload-measures/evaluate-progress-with-staff.md`
- `/workload-reduction-toolkit/evaluate-workload-measures/staff-workload-survey.md`
- `/workload-reduction-toolkit/evaluate-workload-measures/structured-conversations-with-staff.md`
We used the figma designs where available and updated the text where appropriate based on the change log.
> Add evaluate resources

- content/accessibility-statement.md
- layouts/base.html.erb
Card: [Create accessibility statement page](https://trello.com/c/dL6Ervtm)
Adding the Accessibility page and updating the footer link.
> Add accessibility statement

- .github/workflows/publish.yml
- Rules
- lib/helpers.rb
- nanoc.yaml
This PR implements updates to the handling of `base_url` across different parts of our application, particularly for Netlify previews and production environments. It introduces modifications to the GitHub Actions workflow, the `Rules` file, the `helpers.rb` file, and the `nanoc.yaml` configuration to ensure consistent and correct base URLs are used.
- **GitHub Actions Workflow (`publish.yml`):**
- Introduced the `NANOC_ENV` environment variable in the build site job, setting it to `production`. This change ensures that our build process is explicitly defined for the production environment.
- Updated the artifact upload path syntax from single quotes to double quotes, aligning with standard YAML practices.
- **Rules File Enhancement (`Rules`):**
- Added a preprocess block to dynamically …
> Enhance Base URL Configuration for Improved Netlify Previews and Production Consistency

- content/staff-wellbeing/academy-trust-workload-agreement.md
- content/staff-wellbeing/communicate-about-wellbeing-to-improve-staff-retention.md
- content/staff-wellbeing/create-a-school-culture-which-improves-wellbeing.md
- content/staff-wellbeing/establish-a-school-workload-group.md
- content/staff-wellbeing/establish-a-wellbeing-committee.md
- content/staff-wellbeing/make-a-list-of-everything-you-do-to-improve-wellbeing.md
- content/staff-wellbeing/protect-staff-time-and-improve-wellbeing.md
- content/staff-wellbeing/staff-wellbeing-policy.md
- content/staff-wellbeing/staff-wellbeing-statement.md
- content/staff-wellbeing/wellbeing-and-workload-charter.md
- content/workload-reduction-toolkit/address-workload-issues/behaviour-management/review-and-streamline-behaviour-management.md
- content/workload-reduction-toolkit/address-workload-issues/behaviour-management/set-up-a-centralised-system-to-record-monitor-and-reward-pupil-behaviour.md
- content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/change-lesson-observations-to-class-visits.md
- content/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/use-time-effectively.md
- content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/give-feedback-effectively-without-creating-an-unmanageable-workload.md
- content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/improve-how-you-give-feedback-to-primary-pupils.md
Ensure all bullets consistently formatted.
> [xxx] Make bullet points consistently formatted in .md files

- content/accessibility-statement.md
Now you can skip to the main content, change:
```
We know some parts of this website are not fully accessible:
- you cannot modify the line height or spacing of text
- you cannot skip to the main content when using a screen reader
```
To:
`We know the service is not fully accessible because you cannot modify the line height or spacing of text.`
https://trello.com/c/TKWtWkVp/415-update-accessibility-statement
> Update accessibility statement

- layouts/partials/resource_card_with_image.html.erb
https://github.com/DFE-Digital/improve-workload-and-wellbeing-for-school-staff/assets/85567720/bca2c57d-412f-4587-8da5-8e1070419be3
> Tidy up supporting resources on mobile

- README.md
- docs/reviewing-pull-request.md
This update introduces a comprehensive guide aimed at empowering non-developer team members to actively participate in the PR review process. The guide covers essential aspects such as suggesting changes on specific lines, general commenting, verifying links, and assessing mobile responsiveness.
- Added detailed instructions on how to suggest changes to specific lines in a PR, enhancing precision in feedback.
- Included guidelines for leaving both line-specific and general comments, facilitating clearer communication.
- Introduced a step-by-step process for checking the functionality of links within the PR, ensuring all resources are accessible and correct.
- Updated the mobile responsiveness section to incorporate the use of the QR code provided by the Netlify bot, allowing for …
> Docs: Reviewing a Pull request

- content/workload-reduction-toolkit/address-workload-issues/behaviour-management/review-and-streamline-behaviour-management.md
- content/workload-reduction-toolkit/address-workload-issues/communications/streamline-internal-school-communications.md
- content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/cut-down-your-marking-workload.md
- content/workload-reduction-toolkit/evaluate-workload-measures/update-your-workload-action-plan.md
- content/workload-reduction-toolkit/identify-workload-issues/create-an-action-plan-to-reduce-workload.md
- content/workload-reduction-toolkit/identify-workload-issues/staff-workload-survey.md
- content/workload-reduction-toolkit/identify-workload-issues/use-an-inset-day-to-focus-on-reducing-workload.md
Fixing a few typos we've noticed on the service.
> Fix minor typos

- content/staff-wellbeing/make-a-list-of-everything-you-do-to-improve-wellbeing.md
- content/staff-wellbeing/staff-wellbeing-policy.md
- content/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/cut-down-your-marking-workload.md
Update/remove contact details as per these Trello cards:
https://trello.com/c/lafaAW60/451-update-contributors-details-on-two-pages
https://trello.com/c/GDUQWmJl/455-remove-contributors-details-on-one-page
Removal:
https://deploy-preview-151--iwwss-review.netlify.app/staff-wellbeing/staff-wellbeing-policy/
Updates:
https://deploy-preview-151--iwwss-review.netlify.app/staff-wellbeing/make-a-list-of-everything-you-do-to-improve-wellbeing/
https://deploy-preview-151--iwwss-review.netlify.app/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/cut-down-your-marking-workload/
> 451/455 Update contact details

- content/explore-all-resources/attendance.html.erb
- content/workload-reduction-toolkit/address-workload-issues.html.erb
- content/workload-reduction-toolkit/address-workload-issues/attendance.html.erb
- content/workload-reduction-toolkit/address-workload-issues/attendance/improve-school-attendance-by-supporting-pupils-parents-and-carers.md
- layouts/partials/topic_list.html.erb
- layouts/workload_topic_section.html.erb
- Add new case study
- Also adds new topic `Attendance`
> add improve attendance case study
